"use client";
// Lane B owns these strings until the captain merges them into messages/en.json.
// useApplyT() asks the shared dictionary first and falls back to the table below,
// so the Secure Zone keeps working before and after the merge.
import { useT } from "@/lib/i18n";

export const APPLY_STRINGS: Record<string, string> = {
  "apply.title": "Secure application",
  "apply.noai": "No AI reads this page.",
  "apply.noai.field": "This page is not read by any AI.",
  "apply.step": "Step {n} of {total}",
  "apply.elapsed": "{m}:{s} elapsed",
  "apply.why": "Why we ask",
  "apply.back": "Back",
  "apply.next": "Continue",
  "apply.submit": "Submit application",
  "apply.simulated": "Simulated",
  "apply.saved": "Saved",
  "apply.startover": "Start over",
  "apply.cip.title": "Why we ask for this",
  "apply.and": "and",
  "apply.sample.fill": "Use sample data",
  "apply.sample.note": "Fills this step with invented details so a demo does not need ten typed fields.",
  "apply.review.name": "Name",
  "apply.accounts.money": "{min} to open, {fee} monthly",
  "apply.accounts.applied": "Verified once, applied to {names}.",
  "apply.optional": "Optional",
  "apply.prefilled": "From your conversation",

  "apply.step1.title": "Your path",
  "apply.step2.title": "About you",
  "apply.step3.title": "Verify you",
  "apply.step3.sub": "Two photos, four checks, one readout. Nothing leaves this page; the checks are simulated.",
  "apply.step4.title": "Your accounts",
  "apply.step5.title": "Review and submit",
  "apply.cip": "Federal rules require your name, date of birth, address, and an identification number before an account opens. We ask once, here, with the reason next to each field.",

  "apply.path.ssn": "I have a Social Security number",
  "apply.path.ssn.sub": "The usual path for U.S. citizens and permanent residents.",
  "apply.path.itin": "I have an ITIN",
  "apply.path.itin.sub": "An IRS tax number works in place of an SSN.",
  "apply.path.foreign_status": "I do not have either yet (passport and student documents)",
  "apply.path.foreign_status.sub": "Open with a passport and your school documents. No SSN needed.",
  "apply.path.minor": "I am under 18",
  "apply.path.minor.sub": "Teen accounts are signed with a parent or guardian.",
  "apply.path.branch_assist": "I would rather do this with a banker",
  "apply.path.branch_assist.sub": "We hold your place and a banker finishes it with you.",
  "apply.checklist.title": "What you will need",
  "apply.checklist.heading": "What You'll Need",
  "apply.notes.title": "Good to know",

  "apply.doc.gov_id": "A government photo ID: driver license, state ID, military ID, U.S. passport, or permanent resident card",
  "apply.doc.ssn": "Your Social Security number",
  "apply.doc.address": "Your Austin address (no P.O. boxes)",
  "apply.doc.gov_id_itin": "A government photo ID: passport, consular ID, or state ID",
  "apply.doc.itin": "Your ITIN letter or card",
  "apply.doc.address_proof": "Proof of your Austin address: lease, utility bill, or UT housing letter",
  "apply.doc.passport": "Your passport",
  "apply.doc.i20": "Your I-20 or DS-2019",
  "apply.doc.w8ben": "W-8BEN acknowledgment, which you check in step 2",
  "apply.doc.school_id": "Your school ID or state ID",
  "apply.doc.guardian": "A parent or guardian, with their own government photo ID",
  "apply.doc.any_id": "Whatever ID you have, even if it is expired or incomplete",
  "apply.doc.any_address": "Anything with your Austin address on it",
  "apply.note.savings_member": "Savings opens with $1 and is what makes you a member.",
  "apply.note.anyone_can_join": "Anyone can join UFCU. You do not have to be a UT student.",
  "apply.note.no_ssn_needed": "No SSN needed to open; you can add one later if you get one.",
  "apply.note.zelle_ssn": "Zelle requires an SSN. Wires and transfer services work in the meantime.",
  "apply.note.no_ssn_needed_later": "No SSN needed to open; you can add an SSN or ITIN later.",
  "apply.note.zelle_ssn_intl": "Zelle requires an SSN. Use a wire or an international transfer service for now.",
  "apply.note.new_address_video": "A new address often means a five-minute video call with a banker before the account opens.",
  "apply.note.teen_checking": "Teen Checking covers ages 13 to 17.",
  "apply.note.guardian_signs": "A parent or guardian signs with you at the University Branch, so this path finishes in person.",
  "apply.note.banker_sorts": "A banker sorts the rest with you in person. Nothing here is a dead end.",

  "apply.f.firstName": "First name",
  "apply.f.lastName": "Last name",
  "apply.f.dob": "Date of birth",
  "apply.f.email": "Email",
  "apply.f.phone": "Phone",
  "apply.f.street": "Street address",
  "apply.f.city": "City",
  "apply.f.state": "State",
  "apply.f.zip": "ZIP code",
  "apply.f.occupation": "Occupation",
  "apply.f.affiliation": "School or employer",
  "apply.f.ssn": "Social Security number",
  "apply.f.itin": "ITIN",
  "apply.f.passport": "Passport number",
  "apply.f.country": "Country that issued it",
  "apply.f.w8ben": "I am not a U.S. person and will complete a W-8BEN",
  "apply.show": "Show",
  "apply.hide": "Hide",

  "apply.why.name": "Your legal name is one of the four items federal rules require before an account opens.",
  "apply.why.dob": "Date of birth is required to confirm you are the person on the ID.",
  "apply.why.email": "We send your account documents and disclosures here, not paper.",
  "apply.why.phone": "We call this number only to reach you about your application or a fraud alert.",
  "apply.why.address": "A physical address is required before an account opens; a P.O. box cannot be used.",
  "apply.why.occupation": "Occupation helps us spot activity that does not match the account later on.",
  "apply.why.affiliation": "Affiliation is optional and only shows which membership route applies.",
  "apply.why.ssn": "An identification number is required before an account opens; for a U.S. person that is a taxpayer ID.",
  "apply.why.itin": "An ITIN is the taxpayer ID the rule accepts when you do not have an SSN.",
  "apply.why.passport": "For a non-U.S. person the identification number can be a passport number.",
  "apply.why.country": "The issuing country tells us which document standard to check the passport against.",
  "apply.why.w8ben": "The IRS asks non-U.S. persons to certify foreign status on a W-8BEN instead of a W-9.",

  "apply.step3.lead": "We check the details you gave us first. Most people finish here; if something cannot be confirmed, we ask for a document and a selfie instead of sending you to a branch.",
  "apply.stage1.title": "Checking your information",
  "apply.stage1.body": "We are checking the details you gave us against the records a credit union is required to check",
  "apply.stage1.consistency": "Data consistency",
  "apply.stage1.watchlist": "Watchlist",
  "apply.stage1.idNumber": "ID number match (SSN or ITIN)",
  "apply.stage1.noTaxId": "No U.S. taxpayer number on file",
  "apply.stage1.checking": "Checking",
  "apply.stage1.progress": "Checking the details you gave us...",
  "apply.stage1.confirmed": "We confirmed your details. Nothing else is needed for identity.",
  "apply.stage1.unconfirmed": "We could not confirm everything from your details",
  "apply.stepup.title": "One more thing: confirm it is you",
  "apply.stepup.why": "Today's flow stops here and sends you to a branch. Instead, we ask for a government ID and a quick selfie online, the same extra line of defense large banks already run.",
  "apply.stepup.vendorLabel": "Identity verification service",
  "apply.stepup.vendor": "Placeholder for a third-party identity verification service (document authenticity and liveness). Simulated in this prototype.",

  "apply.verify.id": "Government ID",
  "apply.verify.selfie": "Selfie",
  "apply.verify.enrollment": "Enrollment document (I-20 or DS-2019)",
  "apply.verify.drop": "Drag a photo here, or",
  "apply.verify.sample": "Use sample",
  "apply.verify.loaded": "Sample loaded",
  "apply.verify.run": "Verify",
  "apply.verify.running": "Verifying",
  "apply.verify.again": "Run again",
  "apply.trust.title": "Identity readout",
  "apply.trust.heading": "Identity Check",
  "apply.trust.document": "Document authenticity",
  "apply.trust.face": "Face match",
  "apply.trust.consistency": "Data consistency",
  "apply.trust.watchlist": "Sanctions and watchlist",
  "apply.trust.pass": "Pass",
  "apply.trust.review": "Review",
  "apply.trust.fail": "Fail",
  "apply.trust.notNeeded": "Not needed",
  "apply.trust.how": "How we decided",
  "apply.trust.how.instant": "Your details matched, so no document was needed.",
  "apply.trust.how.stepup": "Your details could not be fully matched, so we confirmed your identity with a document and a selfie instead of a branch visit.",
  "apply.trust.confidence": "Confidence {n} of 100",
  "apply.trust.confidenceLabel": "Confidence out of 100",
  "apply.trust.note": "In production these checks map to a KYC vendor and the core; today they are simulated.",
  "apply.detail.doc.ok": "The sample ID scanned clean and the security features matched.",
  "apply.detail.face.ok": "Your selfie matched the photo on the ID.",
  "apply.detail.consistency.ok": "Your name, date of birth, and address line up across the documents.",
  "apply.detail.consistency.new": "Your address is only a few weeks old, so a banker will confirm it.",
  "apply.detail.doc.notNeeded": "No document was needed; your details matched the records we check.",
  "apply.detail.face.notNeeded": "No selfie was needed; your details matched the records we check.",
  "apply.detail.watchlist.ok": "No match on the sanctions and watchlist files.",
  "apply.detail.minor": "Under 18, a parent or guardian signs with you in person.",

  "apply.outcome.verified.title": "You're verified.",
  "apply.outcome.verified.body": "Your details matched what we're required to check. Nothing else is needed for identity.",
  "apply.outcome.stepup.title": "One more thing to confirm it's you.",
  "apply.outcome.stepup.body": "We couldn't confirm everything from your details. Instead of sending you to a branch, we can finish online with a photo of your government ID and a quick selfie. Our identity partner checks them in seconds.",
  "apply.outcome.video.title": "Almost there. A banker will finish this with you.",
  "apply.outcome.video.body": "One detail needs a quick look from a person. Pick a five-minute video call, or stop by the University Branch.",
  "apply.outcome.video.orBranch": "Or stop by in person",
  "apply.outcome.branch.title": "Let's finish this together at a branch.",
  "apply.outcome.branch.body": "A banker will finish this with you in person, and you will leave with the account open.",
  "apply.outcome.branch.orVideo": "Or book a five-minute video call instead",
  "apply.demo.how": "Demo: how the system decided (not shown to members)",

  "apply.route.instant.title": "Verified. Your accounts can open now.",
  "apply.route.instant.body": "Nothing else is needed from you for identity.",
  "apply.route.video.title": "A five-minute video call with a banker",
  "apply.route.video.body": "One item needs a human look. Pick a time today and a banker at the University Branch will confirm it with you.",
  "apply.route.video.pick": "Times today",
  "apply.route.video.picked": "Booked for {time} today.",
  "apply.route.branch.title": "Finish at the University Branch",
  "apply.route.branch.body": "This path is signed in person. Bring your documents and your parent or guardian.",
  "apply.branch.hours": "Monday to Friday, 10 AM to 4 PM",

  "apply.accounts.sub": "Verified once, applied to every account in this bundle.",
  "apply.accounts.membership": "Membership account. Always included.",
  "apply.accounts.memberPill": "Membership account",
  "apply.accounts.add": "Add",
  "apply.accounts.remove": "Remove",
  "apply.accounts.included": "Included",
  "apply.accounts.min": "{v} to open",
  "apply.accounts.fee": "{v} monthly fee",
  "apply.disclosures.title": "What you are agreeing to",
  "apply.disclosure.esign": "Documents by email (ESIGN consent)",
  "apply.disclosure.esign.sub": "You agree to receive statements, notices, and disclosures electronically. You can ask for paper any time.",
  "apply.disclosure.agreement": "Membership and Account Agreement",
  "apply.disclosure.agreement.sub": "The rules for the account: fees, how deposits clear, and UFCU's right to apply your deposits to what you owe it.",
  "apply.disclosure.w8ben": "Certification of foreign status (W-8BEN)",
  "apply.disclosure.w8ben.sub": "You certify you are not a U.S. person for tax purposes and will complete the IRS form.",
  "apply.disclosure.read": "Read the full document",

  "apply.review.edit": "Edit",
  "apply.review.path": "Your path",
  "apply.review.about": "About you",
  "apply.review.verify": "Verification",
  "apply.review.identity.instant": "Identity: verified from your details",
  "apply.review.identity.stepup": "Identity: confirmed with ID and selfie",
  "apply.review.accounts": "Your accounts",
  "apply.review.masked": "Kept on this page only",
  "apply.review.memory": "Your ID number stays in this browser tab. It is masked here and never written to storage, so a refresh asks for it again.",
  "apply.submitting": "Submitting",
  "apply.decision.approved.title": "You are a member. Your accounts are open.",
  "apply.decision.approved.body": "Your account numbers arrive by email in a few minutes. Nothing else is needed today.",
  "apply.decision.needs.title": "One more thing and you are done",
  "apply.decision.needs.how": "How to finish",
  "apply.decision.notyet.title": "Not this account yet, and here is what works instead",
  "apply.decision.alternatives": "What we can open today",
  "apply.credit.approved.title": "Approved for the UFCU Visa",
  "apply.credit.approved.step": "Your card arrives by mail in about a week; activate it in the app when it lands.",
  "apply.credit.notyet.title": "Not yet for the credit card",
  "apply.credit.notyet.reason": "We can't approve the UFCU Visa today because there isn't enough credit history yet. That's normal for a first account, and it's exactly what these two options fix.",
  "apply.credit.alt.builder.title": "Credit Builder Loan",
  "apply.credit.alt.builder.body": "The money sits in your savings while the payments get reported to the credit bureaus. You get the deposit back at payoff, and this one is approved today.",
  "apply.credit.alt.secured.title": "Secured Visa",
  "apply.credit.alt.secured.body": "The same UFCU Visa, backed by a deposit you set aside. Rates are capped by federal credit union rules, and it becomes a regular card once you have a history.",
  "apply.credit.add": "Add to my application",
  "apply.credit.comeback": "Come back in about six months and we'll look again.",
  "apply.next.title": "Next steps",
  "apply.next.open": "Open on ufcu.org",
  "apply.done.elapsed": "Start to finish: {m}:{s}",
  "apply.done.compare": "The same opening today takes two hosts, a branch appointment, and a callback.",

  "apply.next.deposit.title": "Move your paycheck here",
  "apply.next.deposit.detail": "Give your employer routing number 314977405 and your new account number. UT campus jobs change it in Workday.",
  "apply.next.digital.title": "Enroll in digital banking",
  "apply.next.digital.detail": "Set up the app first; every other step below happens inside it.",
  "apply.next.atm.title": "Fee-free ATMs on campus",
  "apply.next.atm.detail": "Student Services Building, Gregory Gym, PCL, and RLM take deposits. The Union ATM does not.",
  "apply.next.zelle.title": "Zelle needs a Social Security number",
  "apply.next.zelle.detail": "Until you add one, pay friends by wire or another transfer service. You can add an SSN or ITIN later.",
  "apply.next.credit.title": "Credit Builder Loan",
  "apply.next.credit.detail": "The money sits in your savings while the payments get reported to the bureaus. You get the deposit back at payoff.",
  "apply.next.atm.any.title": "Fee-free ATMs near you",
  "apply.next.atm.any.detail": "UFCU's ATM map shows the machines you can use without a fee, including shared network ATMs.",
  "apply.next.switchkit": "Switch Kit",
  "apply.next.switch.deposit.title": "Re-point your direct deposit first",
  "apply.next.switch.deposit.detail": "Everything else is easier once the paycheck lands here.",
  "apply.next.switch.autopay.title": "List your autopays and move them",
  "apply.next.switch.autopay.detail": "Rent, phone, insurance, subscriptions. Work from last month's statement so nothing is missed.",
  "apply.next.switch.keep.title": "Keep the old account open one statement cycle",
  "apply.next.switch.keep.detail": "It catches anything you forgot to move before you close it.",
  "apply.next.switch.close.title": "Then close the old account",
  "apply.next.switch.close.detail": "Ask for the balance by check or transfer, and get the closure in writing.",

  "apply.err.path": "Pick the path that matches your documents.",
  "apply.err.firstName": "Enter your first name.",
  "apply.err.lastName": "Enter your last name.",
  "apply.err.dob": "Use MM/DD/YYYY, like 03/14/2005.",
  "apply.err.email": "Enter an email like you@example.com.",
  "apply.err.phone": "Enter a 10-digit phone number.",
  "apply.err.street": "Enter your street address. A P.O. box cannot be used.",
  "apply.err.city": "Enter your city.",
  "apply.err.state": "Use the two-letter state code, like TX.",
  "apply.err.zip": "Enter a 5-digit ZIP code.",
  "apply.err.occupation": "Enter your occupation, or write Student.",
  "apply.err.ssn": "Enter 9 digits, like 123-45-6789.",
  "apply.err.itin": "An ITIN is 9 digits and starts with a 9.",
  "apply.err.passport": "Enter the passport number exactly as printed.",
  "apply.err.country": "Enter the country that issued your passport.",
  "apply.err.w8ben": "Check this so we can file your W-8BEN.",
  "apply.err.docs": "Add your ID and a selfie, or press Use sample.",
  "apply.err.enrollment": "Add your I-20 or DS-2019, or press Use sample.",
  "apply.err.verify": "Run the check so we can show you the readout.",
  "apply.err.slot": "Pick a time for the video call.",
  "apply.err.products": "Savings is the membership account and stays in the bundle.",
  "apply.err.esign": "Agree to receive your documents by email.",
  "apply.err.agreement": "Agree to the Membership and Account Agreement.",
};

function fill(text: string, vars?: Record<string, string | number>): string {
  if (!vars) return text;
  let out = text;
  for (const [k, v] of Object.entries(vars)) out = out.replaceAll(`{${k}}`, String(v));
  return out;
}

export function useApplyT() {
  const t = useT();
  return (key: string, vars?: Record<string, string | number>) => {
    const shared = t(key, vars);
    if (shared !== key) return shared;
    const local = APPLY_STRINGS[key];
    return local ? fill(local, vars) : fill(key, vars);
  };
}
